services:
  web:
    image: ghcr.io/axelgoris99/chroma-notes:latest
    container_name: chroma-notes
    volumes:
      - jobs_data:/app/jobs
    restart: unless-stopped
    mem_limit: 6g
    environment:
      - JOBS_DIR=/app/jobs
      - USE_MODAL=1
      - MODAL_TOKEN_ID=${MODAL_TOKEN_ID}
      - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET}
    networks:
      - caddy

volumes:
  jobs_data:

networks:
  caddy:
    external: true
    name: debian_default
